# Generated by Django 3.1.3 on 2020-12-28 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='USN',
            new_name='student_id',
        ),
    ]
